### ISSUE TITLE
Updating to 2020.3 EAP downgrades poetry plugin

### ISSUE THREAD

**Issue by thuringia** [koxudaxi/poetry-pycharm-plugin#111]
**Describe the bug**
After updating to 2020.3 EAP version 0.5 of the plugin disappears from the marketplace.

Interestingly enough, it appears that all features of 0.5 work. The package manger UI is filled correctly as is the virtualenv integration.

**To Reproduce**
1. Install plugin on 2020.2
2. Make version 0.5.0 a required plugin
3. Upgrade to 2020.3 EAP
4. See error "version 0.5 is required but 0.1.2 is installed"

**Expected behavior**
The correct version should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/752104/94120414-5d0a0d00-fe50-11ea-8d7b-b33d1db11f38.png)
![image](https://user-images.githubusercontent.com/752104/94120476-714e0a00-fe50-11ea-803a-1d8ed4d1812b.png)

**Environments (please complete the following information):**
 - IDE: IntelliJ IIntelliJ IDEA 2020.3 EAP (Ultimate Edition), Build #IU-203.3645.34, built on September 21, 2020
 - OS: running in WSL (ArchLinux) on Windows 10
 - Poetry Version 1.0.10
 - Plugin version 0.5?

**Comment by koxudaxi** [comment]
@thuringia 
Thank you for creating this issue.
I have applied a fixed version to JetBrains Market.
They will approve the request in two business days.
I will post the information here when It's published.

**Comment by koxudaxi** [comment]
@thuringia 
version 0.5.1 is approved by JetBrains. 
You can use the plugin on PyCharm 2020.3 EAP.
