### ISSUE TITLE
Poetry plugin prevents inspections to be visible in settings

### ISSUE THREAD

**Issue by akittas** [koxudaxi/poetry-pycharm-plugin#114]
**Describe the bug**
No inspections are visible in the settings window, we are presented with a blank page.
Disabling or removing the plugin fixes the problem.

**Screenshots**
![2020-09-26](https://user-images.githubusercontent.com/2411041/94348041-ee8ca100-0041-11eb-8a4e-8c6c08645787.png)

**To Reproduce**
Open Settings -> Editor -> Inspections

**Expected behavior**
Inspections settings should be visible.

**Environments:**
 - IDE: PyCharm Professional 2020.2.2
 - OS: Microsoft Windows 10 [Version 10.0.19041.508]
 - Poetry version: 1.0.10
 - Plugin version: 0.5.1

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I have reproduced this problem.
I will create a PR to fix it soon.

**Comment by koxudaxi** [comment]
@akittas  
The fixed version has been published as 0.5.2
