### ISSUE TITLE
Plugin Poetry v0.5.2 is incompatible with last version of IntelliJ

### ISSUE THREAD

**Issue by cruzelante098** [koxudaxi/poetry-pycharm-plugin#118]
**Describe the bug**
The Poetry plugin v0.5.2 does not appear on the IntelliJ marketplace. v0.1.3 does appear.

I tried to install it manually and IntelliJ threw the next error:

```
Plugin 'Poetry' version 0.5.2 is incompatible with this installation: since build 202.7319.64 > IU-202.7319.50
```

**To Reproduce**
1. Using IntelliJ 2020.2.2, build 202.7319.50
2. Download Poetry 0.5.2
3. Go to Plugins > ⋮ > Install plugin from disk
4. Select poetry plugin
5. See error

**Expected behavior**
1. The last version of the plugin should show up in the maketplace. It doesn't.
2. Should be able to install the last version manually.

**Screenshots**
![demo](https://user-images.githubusercontent.com/22967094/94909214-c3b7a800-049a-11eb-9c83-c82b77b5356c.gif)

**Environments (please complete the following information):**
 - IDE: IntelliJ 2020.2.2, build 202.7319.50
 - OS: Windows 10 v2004
 - Poetry Version 1.1.0
 - Plugin version 0.5.2

**Comment by koxudaxi** [comment]
@cruzelante098 
Thank you for creating this issue.
Oh, I'm sorry I didn't care IntelliJ versions.
I will resolve the dependency.

**Comment by cruzelante098** [comment]
v0.5.3 works with IntelliJ 2020.2.2 #IU-202.7319.50. I'm closing this issue.

Thank you @koxudaxi
