### ISSUE TITLE
Error creating a new project

### ISSUE THREAD

**Issue by MushroomMaula** [koxudaxi/poetry-pycharm-plugin#123]
**Describe the bug**
When I try to create a new flask project with poetry as its enviroment I get the following [error](https://imgur.com/a/qOEZVlT).
Running the command myself in my user directory I get this error:
`
[RuntimeError]
Poetry could not find a pyproject.toml file in C:\Users\Max or its parents
`
I assume PyCharm is not setting the working directory correctly when running the command

**Environments (please complete the following information):**
 - IDE: PyCharm 2020.2.3 (Professional Edition) Build #PY-202.7660.27, built on October 6, 2020
 - OS:  Windows 10 
 - Poetry Version 1.0.10
 - Plugin version 0.5.3

**Comment by koxudaxi** [comment]
@MushroomMaula 
Thank you for creating this issue.
I have created a new flask project with poetry in windows 10.
However, It works fine.

How did you install poetry?

**Environments (please complete the following information):**
 - IDE: PyCharm 2020.2.3 (Professional Edition) Build #PY-202.7660.27, built on October 6, 2020
 - OS: Windows 10 
 - Poetry Version 1.1.2
 - Plugin version 0.5.3

![VirtualBox_Windows 10_11_10_2020_01_11_32](https://user-images.githubusercontent.com/630670/95659889-1c540880-0b5f-11eb-9c30-cce4839c08cc.png)

This code sets the working directory for the poetry command.
https://github.com/koxudaxi/poetry-pycharm-plugin/blob/0ee3cbf4225c3b5e8bbaec9b71dac2db191414f2/src/com/koxudaxi/poetry/poetry.kt#L261

**Comment by MushroomMaula** [comment]
Well I just updated poetry to version 1.1.2 and after trying again it works just fine so I assume it's an error on poetry's side.

PS: I used [get-poetry.py](https://github.com/python-poetry/poetry/blob/master/get-poetry.py) for installing poetry
