### ISSUE TITLE
Wrong system interpreter icon in settings

### ISSUE THREAD

**Issue by akittas** [koxudaxi/poetry-pycharm-plugin#125]
**Describe the bug**
System interpreter icon is wrong. System interpreter is shown with virtualenv-like icon (i.e. python logo **with V**) instead of system icon (plain python logo).

**To Reproduce**
1. Go to Interpreter Settings
2. Add a System Interpreter
3. Open Interpreter settings again and notice System Interpreter icon

**Expected behavior**
A system interpreter should have a plain python icon, not a virtualenv-like icon (see screenshots below). First screenshot is without the plugin and second screenshot (with the wrong icon) is with the plugin.

**Screenshots**
![icon1](https://user-images.githubusercontent.com/2411041/95844766-f8a4e400-0d51-11eb-9cd5-e6cf9c0a4655.jpg)
Correct system interpreter icon (plugin disabled)

![icon2](https://user-images.githubusercontent.com/2411041/95844771-f93d7a80-0d51-11eb-8b28-04fe9af3f0ba.jpg)
Wrong system interpreter icon (plugin enabled)

**Environments (please complete the following information):**
- IDE: PyCharm Professional 2020.2.3
- OS: Microsoft Windows 10 [Version 10.0.19041.508]
- Poetry version: 1.1.2
- Plugin version: 0.5.3

**Comment by koxudaxi** [comment]
@akinnear 
Sorry for my late reply.
I'm confused about why affecting the system interpreter's icon.
I will fix it soon.
Thank you very much.
