### ISSUE TITLE
poetry lock with "--no-update"

### ISSUE THREAD

**Issue by dp-rufus** [koxudaxi/poetry-pycharm-plugin#158]
When I edit my dependencies in `pyproject.toml`, I normally want to run `poetry lock --no-update`, rather than just `poetry lock`.

The plugin UI does not provide a way to do this:

![Screenshot from 2020-12-30 01-01-13](https://user-images.githubusercontent.com/73200607/103323510-0e65a380-4a3b-11eb-923c-f5ff445a2f79.png)

Do you think it would be useful to add an option to use `--no-update`, when the user clicks on "poetry lock"?

Many thanks!

**Comment by koxudaxi** [comment]
@dp-rufus 
Thank you for creating this issue.
I agree with your suggestion.
I released a new version as `1.0.2`
The version provides a button `poetry lock --no-update` on the popup. 
![ 2021-01-06 18 29 35](https://user-images.githubusercontent.com/630670/103841915-001d2480-50d8-11eb-9514-bfadfd92c57d.png)

Thank you very much.

**Comment by dp-rufus** [comment]
This is great! Thank you!
