### ISSUE TITLE
"Failed To Create Interpreter" on Windows

### ISSUE THREAD

**Issue by itsadok** [koxudaxi/poetry-pycharm-plugin#162]
When trying to add a Poetry Environment python interpreter, I'm getting the following error:

`Cannot run program "C:\Users\israel.tsadok\.poetry\bin\poetry" (in directory "C:\Users\israel.tsadok\code\test\poet"): CreateProcess error=193, %1 is not a valid Win32 application`

**To Reproduce**

On Windows:
1. Click the python interpreter button on the bottom right corner of PyCharm
2. Click "Add Interpreter..."
3. Choose "Poetry Environment" on the left-hand side
4. Choose "Python 3.9" as base environment
5. Click OK

**Environment:**
 - IDE: PyCharm Community 2020.3
 - OS: Windows 10 (Build 20279.1)
 - Poetry Version: 1.1.4
 - Plugin version: 1.0.2

**Comment by koxudaxi** [comment]
@itsadok 
Thank you for creating this issue.
I'm sorry for the late reply.

I understand why you got an error.
You should choose `poetry.bat`
<img width="454" alt="poetry bat" src="https://user-images.githubusercontent.com/630670/104297158-de6fd300-5505-11eb-9146-8d792367f9fd.png">


I guess this plugin suggests `poetry.bat` in this setting.
Did you get the suggestion from the plugin?

On windows,  maybe the plugin should try to force to add `.bat` to the poetry path 🤔

**Comment by itsadok** [comment]
Thanks!
It looks like the same "pick any file you like and fail later" approach is used for the pipenv plugin as well. However, when choosing a python interpreter name, there is a [validation function](https://github.com/JetBrains/intellij-community/blob/0781974c1104d2e7766522e48eff34dfe29483ba/python/src/com/jetbrains/python/sdk/PythonSdkType.java#L151) that helps to keep the user from choosing the wrong file.  (It looks like the validation function only verifies that the file name [starts with "python"](https://github.com/JetBrains/intellij-community/blob/ebe036aa2a0f798d6e8baa57f507156734763459/python/python-sdk/src/com/jetbrains/python/sdk/flavors/PythonSdkFlavor.java#L171) though.)

It's odd. From my read of the plugin code, it looks like the plugin should have automatically detected poetry.bat, but I'm sure if it had, I wouldn't have manually switched to the wrong file. Or maybe I did. I don't know. It looks like I would need a fresh installation of PyCharm to try the auto-detection again, because PyCharm remembers the last selected "poetry executable", even after I remove and reinstall the plugin.

In any case, my personal issue is resolved. Feel free to close this issue, or keep it open until you decide whether to add some validation checks on the file name. Thanks again.

**Comment by koxudaxi** [comment]
@itsadok 
I added a validator that runs the selected executable.
The validator calls it with an argument `--version`.
I released a new version `1.0.3`. 🚀
