### ISSUE TITLE
Marked is incompatible for PyCharm EAP while compatible

### ISSUE THREAD

**Issue by BenjaminAfrolabs** [koxudaxi/poetry-pycharm-plugin#179]
**Describe the bug**
Marked is incompatible for PyCharm EAP while compatible

**To Reproduce**
1. Install pycharm EAP
2. Install plugin manually (the marketplace will only install 1.0.3 which is broken)
3. Restart pycharm

**Expected behavior**
Plugin to work without extra steps

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2021.1  (211.4961.30)
 - OS: Windows 10 20H2
 - Poetry Version: 1.1.4
 - Plugin version: 1.0.6

**Additional context**
Work around is to bump the version up in the plugin.xml file in the installed plugin

Having an unrestricted version available on GitHub would also be appreciated if you want to keep the restriction in the marketplace version

**Comment by koxudaxi** [comment]
@BenjaminAfrolabs 
Thank you for creating this issue.
I'm trying to build with `211.4961.22`
The result is a failure. some interfaces are changed.
I will change implementations.

**Comment by BenjaminAfrolabs** [comment]
Looking forward to an official version, it really has made it easier to manage python/poetry

**Comment by koxudaxi** [comment]
I put related changes
https://github.com/JetBrains/intellij-community/commit/6d9e039160dd8ed85f50d44d40262fad0441f774
https://github.com/JetBrains/intellij-community/commit/fb7e5d64147e83e5c7dbf8c50f474f16860b9e1f

**Comment by koxudaxi** [comment]
@BenjaminAfrolabs 
Version `1.1.0` is released, which is for EAP 211. *
