### ISSUE TITLE
Freezing in New Project modal

### ISSUE THREAD

**Issue by ttm56p** [koxudaxi/poetry-pycharm-plugin#197]
**Describe the bug**
In PyCharm, in New Project modal, when typing in location field experiencing freezes.

**To Reproduce**
1. Go to 'New Project' modal.
2. Click on Location input field.
3. Type anything.
4. Observe delays between key stroke and actual appearance of the related symbol in the input field.

**Expected behavior**
Have no freezes when typing in location field of New Project modal.

**Screenshots**
Initially filed a ticket on YouTrack - https://youtrack.jetbrains.com/issue/PY-47597
Here is the video from there - https://youtrack.jetbrains.com/api/files/74-1032861?sign=MTYxNTk5MzIwMDAwMHwxMS02NjUzODd8NzQtMTAzMjg2MXxtOW5KeTdPY29vVFNPNDRtVUJXUVNv%0D%0AaGJYZXk1Q2ItRi1fV2U5THJNUS1rDQo%0D%0A&updated=1615734789076

**Environments (please complete the following information):**
 - IDE: PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021
 - OS: Ubuntu 20.04
 - Poetry Version 1.1.4
 - Plugin version 1.0.7

**Additional context**
There is also thread dump related to that freeze:
[threadDump-20210314-162253.txt](https://github.com/koxudaxi/poetry-pycharm-plugin/files/6136953/threadDump-20210314-162253.txt)

Did minor debugging:
https://github.com/koxudaxi/poetry-pycharm-plugin/blob/e4191dcdec574f547bb197351f9539df4605a28b/src/com/koxudaxi/poetry/PyAddNewPoetryPanel.kt#L177
this method gets invoked many times with same executable argument.

**Comment by koxudaxi** [comment]
@ttm56p 
Thank you for creating this issue.
Interesting!!
This problem may relate to https://github.com/koxudaxi/poetry-pycharm-plugin/issues/196 🤔 

I didn't test on Ubuntu and Other Linux distros.
I will check it on Ubuntu tomorrow.

Would you please tell me the information on installed poetry?
How did you install poetry? install scripts or pipx?
And, I want to know the path of poetry and the file permissions.

**Comment by ttm56p** [comment]
I used install script.
poetry executable is at ~/.poetry/bin/poetry
And perms are 0764 owned by user profile as user and group.

**Comment by ttm56p** [comment]
I also made test build with stacktrace prints.
For each change it does 5 calls of that method.
It looks like that:
[scratch.txt](https://github.com/koxudaxi/poetry-pycharm-plugin/files/6137612/scratch.txt)

**Comment by koxudaxi** [comment]
Thank you for reporting the detail.
I'm working on resolving this problem.
I guess your problem is similar to the issue.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/196
I will report each issue.

**Comment by ttm56p** [comment]
Thank you for developing this plugin!

**Comment by koxudaxi** [comment]
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/162
I added a function checking poetry executable.
But, the function is too heavy and comes freeze.
I will revert it.

**Comment by ttm56p** [comment]
@koxudaxi thank you! In which versions of the plugin you expect this fix to appear?
