### ISSUE TITLE
Suggest existing poetry venvs that are in existing modules

### ISSUE THREAD

**Issue by roxchkplusony** [koxudaxi/poetry-pycharm-plugin#215]
**Is your feature request related to a problem? Please describe.**
When adding a Poetry environment, sometimes the venv already exists and I just want to register it. But the panel only shows the root directory's environment if it exists and is not yet mapped - I would like this to work when there are multiple Poetry projects in the same repo.

**Describe the solution you'd like**
I'd like the dropdown to include all the environments located in existing modules that have not yet been associated.

**Describe alternatives you've considered**
Associating by adding new also works, but it's a lot slower and shows all modules instead of just the ones that don't have SDKs yet. I would like to sweep through and just add ones that I don't have associations for.

**Additional context**

**Comment by koxudaxi** [comment]
@roxchkplusony 
Thank you for posting this suggestion.
Do you create this PR? Or, Should we need to disscue about unclear things first?

**Comment by roxchkplusony** [comment]
I can create it, if you're happy with the pretext. I haven't started on it yet.

**Comment by koxudaxi** [comment]
> I can create it, if you're happy with the pretext. I haven't started on it yet.

No problem!! I'm waiting for your PR.
You don't need to hurry.
Thank you :)
