### ISSUE TITLE
Make it work with PyCharm 212.*

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/poetry-pycharm-plugin#249]
**Is your feature request related to a problem? Please describe.**
The plugin currently does not work with the EAP version of Pycharm 2021.2

**Describe the solution you'd like**
Make it work

**Comment by koxudaxi** [comment]
@chbndrhnns 
Would you please try this version? Poetry 1.1.4-212
https://plugins.jetbrains.com/plugin/14307-poetry/versions/stable/123306

**Comment by BrianPuccio** [comment]
> @chbndrhnns
> Would you please try this version? Poetry 1.1.4-212
> https://plugins.jetbrains.com/plugin/14307-poetry/versions/stable/123306

@koxudaxi: FWIW, PyCharm 2021.2 is out of EAP. I have it installed and your plugin, Poetry 1.1.4-212, and it works fine AFAICT.

Thanks for the excellent work.

**Comment by chbndrhnns** [comment]
It also works for me.

**Comment by koxudaxi** [comment]
Great :smile:

@BrianPuccio
Btw, Sorry I haven't had a chance to say thank you yet :bow: 
Thank you for sponsoring me!!
