### ISSUE TITLE
Support PyCharm 2021.3 EAP

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/poetry-pycharm-plugin#277]
**Is your feature request related to a problem? Please describe.**
I see this message in PyCharm: 

23:35	Plugin error: Plugin 'Poetry' (version '1.1.5-212') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is PY-213.3714.452

**Describe the solution you'd like**
Support the next PyCharm version

**Describe alternatives you've considered**

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
I'm sorry. I don't have the plan for supporting 2021.3 EAP.
Because, This plugin will be merged into the mainstream of PyCharm.
And, the feature will probably be included next EAP. But, It is not decided now.

https://github.com/JetBrains/intellij-community/pull/1736

**Comment by chbndrhnns** [comment]
That's great to hear!thanks for the great work!

**Comment by jgentil** [comment]
This is so awesome!  I am very glad they brought this into mainstream PyCharm!

**Comment by koxudaxi** [comment]
@jgentil 
Thank you for sponsoring me for a long time!!😭 
I'm happy to contribute to the community 😆
