### ISSUE TITLE
8:39 AM	Plugin error: Plugin 'Poetry' (version '1.1.5-212') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is PC-213.4631.9

### ISSUE THREAD

**Issue by Bibinp08** [koxudaxi/poetry-pycharm-plugin#284]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewcrook** [comment]
PyCharm 2021.3 was rolled out today in updates doesn’t seem to be any support for poetry at this stage.

**Comment by koxudaxi** [comment]
https://www.jetbrains.com/pycharm/whatsnew/#poetry-support

I have used this version for poetry.

**Comment by sseveran** [comment]
Does this mean this plugin is being deprecated?

**Comment by koxudaxi** [comment]
@sseveran 
Yes.

PyCharm 2021.3 has the same code as this plugin. (My code is merged.)
So, This plugin will not be supported on PyCharm 2021.3

**Comment by koxudaxi** [comment]
We should write the information at the top of the repository.

**Comment by koxudaxi** [comment]
I just updated README.md
