### ISSUE TITLE
Support for latest PyCharm release (build 213.5744.248)

### ISSUE THREAD

**Issue by williamabreu** [koxudaxi/poetry-pycharm-plugin#300]
**Is your feature request related to a problem? Please describe.**
The plugin just stopped working after the IDE has been updated.
![image](https://user-images.githubusercontent.com/23266568/144420851-1a0023b5-44a6-49ff-8e61-30d96afef4d4.png)

**Describe the solution you'd like**
Make the plugin compatible with the latest release.

**Describe alternatives you've considered**
I can just downgrade the IDE version, but I'm notifying the problem here.

**Additional context**
This is the version I'm using:
![image](https://user-images.githubusercontent.com/23266568/144421149-acc0d666-ae1c-458f-9b77-e3c7326e13b8.png)

**Comment by duongleh** [comment]
@williamabreu As I can see in the release note, the extension is now a part of the PyCharm source code, which means the extension is no longer needed
https://www.jetbrains.com/pycharm/whatsnew/2021-3

**Comment by koxudaxi** [comment]
Yes, My plugin is merged into PyCharm.
We can use the feature natively from PyCharm2021.3 😄 

I will show the information at the top of the GitHub Project page.

**Comment by williamabreu** [comment]
Great! I hadn't seen that yet, thx.
