### ISSUE TITLE
Plugin 'Poetry' (version '1.1.5-212') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223

### ISSUE THREAD

**Issue by sleshJdev** [koxudaxi/poetry-pycharm-plugin#304]
Plugin 'Poetry' (version '1.1.5-212') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223

**Comment by PierrickV** [comment]
Poetry is now part of pycharm thanks to @koxudaxi.
See: https://youtrack.jetbrains.com/issue/PY-30702#focus=Comments-27-5313948.0-0

**Comment by koxudaxi** [comment]
@sleshJdev 
Yes, This plugin has been merged into Pycharm source code 😄 
Python plugin supports poetry integration natively.
We don't need this plugin on 2021.3 or later Jetbrains IDEs.
https://www.jetbrains.com/pycharm/whatsnew/

**Comment by sleshJdev** [comment]
Thanks, good news!
