### ISSUE TITLE
Repair of Broken Env

### ISSUE THREAD

**Issue by DustinMoriarty** [koxudaxi/poetry-pycharm-plugin#36]
It is possible to get into an repairable state if the current interpreter is deleted. I found this while trying out the plugin and deciding to switch from in-project to not in-project.

Steps to reproduce:

1. Configure poetry to use an in-project environment.

```bash
poetry config virtualenvs.in-project true
```
2. Create interpreter using the plugin pointing to a pyenv base interpreter (e.g. ~/.pyenv/versions/3.6.10/bin/python).
3. Delete the in project environment.
```bash
rm -r .venv
```
4. Configure poetry to not use an in project environment.
```bash
poetry config --unset virtualenvs.in-project
```
5. Try to recreate the environment using the plugin. The current environment is listed as invalid. However, the add python interpreter dialogue reads "Poetery (sic) interpreter has been already added, select <name of project>." Therefore, there is no way out of this state.

**Comment by koxudaxi** [comment]
@DustinMoriarty 
Thank you for creating this issue.
I confirmed your case.
I will fix it to re-use an interpreter when re-creating an environment.

**Comment by koxudaxi** [comment]
@DustinMoriarty 
I fixed and released the version as 0.0.8.
Would you please check it?

**Comment by DustinMoriarty** [comment]
@koxudaxi 
Sorry for the late reply. I will give it a try.

**Comment by DustinMoriarty** [comment]
@koxudaxi 
This issue is resolved. Great work!

**Comment by koxudaxi** [comment]
Thanks for your feedback!
I close this issue.
