### ISSUE TITLE
Recognize existing environments from existing projects?

### ISSUE THREAD

**Issue by Rjdrenth** [koxudaxi/poetry-pycharm-plugin#45]
Hi! Loving the plugin! Thanks for taking the effort to build it. 

I would like to suggest that a differentiation can be made between creating a new or adding an existing environment, so that we can register poetry environments that were created prior to installing the plugin, in the same manner you can do that with a Conda or Virtualenv environment.

**Comment by koxudaxi** [comment]
@Rjdrenth 
Thank you for suggesting it.

I will check the source code whether we can implement the feature this weekend 🚀

**Comment by koxudaxi** [comment]
@Rjdrenth 
I have released the feature as `0.0.12`

**Comment by Rjdrenth** [comment]
I just updated and tested it and works perfectly!
As expected, it also recognises and uses the environment in the Terminal and Python Console. 

Many tanks :)
