### ISSUE TITLE
Ability to change where a new env is generated/move already existing venv

### ISSUE THREAD

**Issue by brettroyerr** [koxudaxi/poetry-pycharm-plugin#46]
Would it be possible to change the location of the venv that is created and/or move the location of a previously created venv?

**Comment by koxudaxi** [comment]
@brettroyerr 
Thank you for asking a question.

These operations can not be performed.
But, there is a workaround.
1. change your poetry environment to new_path  (this phase is related to poetry config. you should check poetry documents)
2. change interpreter path to a new path in the pycharm interpreter path. (pycharm GUI settings. )
3. close your project.
4. change the interpreter path to a new path in `${PROJECT_DIR}/.idea/poetry.xml` .
5. re-open the project.

Also, I explain how does this plugin detect the poetry environment.
When you create poetry with the plugin, The plugin writes poetry environment path to a config file where it is `${PROJECT_DIR}/.idea/poetry.xml` .
If the current project interpreter matches the path then, the plugin detects the interpreter is poetry.


example:  `${PROJECT_DIR}/.idea/poetry.xml` 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="PoetryConfigService">
    <option name="poetryVirtualenvPaths">
      <set>
        <option value="$PROJECT_DIR$/.venv/bin/python" />
      </set>
    </option>
  </component>
</project>
```
