### ISSUE TITLE
Create poetry environment when starting a new project 

### ISSUE THREAD

**Issue by MrMrRobat** [koxudaxi/poetry-pycharm-plugin#63]
When creating new project, there are only three options to create new environment:
- Virtualenv
- Pipenv
- Conda

Is it possible to add Poetry in this list or it would require additional API on PyCharm side? 

![image](https://user-images.githubusercontent.com/36469655/84579952-129ddc80-addb-11ea-98e3-dda97fc16b89.png)

### Temporary workaround
Create project with existing python interpreter and then create poetry environment

**Comment by koxudaxi** [comment]
Hi @MrMrRobat 

The feature can not be implemented by the restrictions of PyCharm.
https://github.com/koxudaxi/poetry-pycharm-plugin#feature-restrictions
> Create a new environment when creating a new project.


He is going to start to add APIs (a.k.a extension point) into PyCharm 2020.2 EAP.
The detail is in this issue.
https://github.com/koxudaxi/poetry-pycharm-plugin/issues/58#issuecomment-643668766

**Comment by MrMrRobat** [comment]
Oh, sorry, somehow I missed it. 

I’m glad to see such a great plugin finally working on PyCharm and PyCharm devs are willing to provide full integration for it. Great work, @koxudaxi, thank you!

**Comment by koxudaxi** [comment]
@MrMrRobat 
I have released a new version as 0.5.0 that supports this feature.
This version required PyCharm 2020.2.2 or later.

## Related PR
https://github.com/koxudaxi/poetry-pycharm-plugin/pull/104
