### ISSUE TITLE
Show Python Version in Interpreter Name

### ISSUE THREAD

**Issue by DustinMoriarty** [koxudaxi/poetry-pycharm-plugin#76]
**Is your feature request related to a problem? Please describe.**
I cannot tell which interpreter to use for a given version of python. Because the version appears at the end of the string for poetry interpreters and pycharm uses the beginning of the string, the interpreter names end up being something like this.

Poetry (project-name)
Poetry (project-name) (2)
Poetry (project-name) (3)

**Describe the solution you'd like**
I would like the auto-generated name of the environment to include the python version. 

Desired outcome would be something like the following.
Poetry (project-name-3.6)
Poetry (project-name-3.7)
Poetry (project-name-3.8)

**Describe alternatives you've considered**
Manually editing the name after interpreter creation is not easy using the pycharm UI because it shows all interpreters for all projects in the same form. I cannot set the interpreter name at the time of creation.

**Additional context**
I am using poetry with pyenv on a linux machine.

**Comment by koxudaxi** [comment]
@DustinMoriarty 

Sorry, I lost the notification for your issue.
I think it's a great suggestion.
OK, I will implement it

**Comment by koxudaxi** [comment]
@DustinMoriarty 
The latest version has been released as `0.1.0` 

The plugin creates a name like this.
![Screenshot_2020-07-25_01-36-55](https://user-images.githubusercontent.com/630670/88414344-aa014100-ce17-11ea-9b30-3b0dbf407c91.png)

**Comment by DustinMoriarty** [comment]
Fantastic! I look forward to trying it out!
