### ISSUE TITLE
Poetry Script support

### ISSUE THREAD

**Issue by yu-ichiro** [koxudaxi/poetry-pycharm-plugin#80]
**Is your feature request related to a problem? Please describe.**
You have to open a shell to exec `poetry run script-a`

**Describe the solution you'd like**
I would like to have pycharm to recognize [tool.poetry.scripts] as Run Configurations like NPM scripts area.

**Comment by koxudaxi** [comment]
@yu-ichiro 
Thank you for your suggestion.
OK, I will try it.

**Comment by koxudaxi** [comment]
@yu-ichiro 
I have released a new version as `0.1.1`
Would you please check it?

![Screenshot_2020-08-06_01-48-00](https://user-images.githubusercontent.com/630670/89440644-e2453f80-d786-11ea-9094-4f87e4b97bd5.png)

**Comment by yu-ichiro** [comment]
Wow that was fast 😳
I'll look into it tomorrow! Thank you very much!

**Comment by yu-ichiro** [comment]
@koxudaxi 
Sorry for not being in touch. I got it to test it, and it's working pretty well!
I however have a problem. I can't access the stdin for the program, so I can't stop a script with Ctrl-C or something. I would like it to bind stdin also😀

I would also really appreciate if it created&bind to a run configuration that I can run/stop from the toolbar, and asked me when I quit PyCharm if I wanted to detach the running script and make it keep running in the background even after PyCharm is killed, or make it die with the PyCharm process.

Thanks for your awesome work!

**Comment by koxudaxi** [comment]
> I however have a problem. I can't access the stdin for the program, so I can't stop a script with Ctrl-C or something. I would like it to bind stdin also :grinning:

@yu-ichiro 

Yes, The console is read-only `view console` which is not `terminal` with `stdin`  :crying_cat_face: 
However, I guess I change `view console` to `terminal` very hard.

I have forgotten about a run configuration. I feel that It is better than `view console`.

I don't know how do I add the run configuration to run scripts. :thinking: 
I will find a way and implement it. :rocket:

**Comment by mLewisLogic** [comment]
Thanks! A run config would be great. That would make supporting args very simple.

**Comment by mLewisLogic** [comment]
(Also wondering if a run configuration might also make debug breakpoints possible?)

**Comment by koxudaxi** [comment]
@mLewisLogic 

> (Also wondering if a run configuration might also make debug breakpoints possible?)

Sorry, I don't know about it. 
I will learn it this weekend. :book: 
First, I will read this document for a plugin developer.
https://jetbrains.org/intellij/sdk/docs/basics/run_configurations.html

Currently, the plugin calls `poetry run script`.
But, I guess the plugin has to execute a python interpreter directly to connect debugger.

I don't understand inside poetry.  I may ask poetry teams about detail.

**Comment by koxudaxi** [comment]
@yu-ichiro @mLewisLogic @abn 
I have changed behavior to use RunConfiguration.
This feature creates RunConfiguration and executes one.
Also, If there isn't a script in `bin`, then show error dialog with a message. Users can know they have to execute `poetry install` before doing this feature.
It's published after JetBrains approval. we need to wait for about two days.

![Peek 2020-09-03 03-33](https://user-images.githubusercontent.com/630670/92024605-5a5c5080-ed99-11ea-9961-4bb24785c112.gif)

**Comment by mLewisLogic** [comment]
That's beautiful! Thank you @koxudaxi!

**Comment by yu-ichiro** [comment]
This is mind-blowing!!! It works perfectly! Thank you for the beautiful work @koxudaxi

**Comment by koxudaxi** [comment]
@mLewisLogic 
I am very happy that you were glad!!

@yu-ichiro 
Thank you for sponsoring me!! 
Also, Your suggest improves the plugin :smile: 

I believe the community grows up software.
Welcome PRs and comments :nerd_face:
