### ISSUE TITLE
error when adding interpreter

### ISSUE THREAD

**Issue by KrunchMuffin** [koxudaxi/poetry-pycharm-plugin#89]
I am trying to install a new interpreter in pycharm with this plugin on windows 10 home with pycharm 2020.1. I am missing fields that you show in your screenshot and I get an error when trying to point to poetry.bat.

![image](https://user-images.githubusercontent.com/1037197/90342518-e2d7a480-dfd6-11ea-8841-069bb9c7462f.png)

**Comment by koxudaxi** [comment]
@KrunchMuffin 
Thank you for creating this issue.

> I am trying to install a new interpreter in pycharm with this plugin 

Have you not installed any python interpreter in your windows yet? 
If you have already installed a python interpreter, Would you please tell the path of an interpreter?

This plugin may need an installed Python interpreter. :thinking:

**Comment by KrunchMuffin** [comment]
You mean in my project or globally? I didn't have one set up yet in the
project.


On Aug 17, 2020 at 3:51 PM, Koudai Aono <notifications@github.com> wrote:

@KrunchMuffin <https://github.com/KrunchMuffin>
Thank you for creating this issue.

I am trying to install a new interpreter in pycharm with this plugin

Have you not installed any python interpreter in your windows yet?
If you have already installed a python interpreter, Would you please tell
the path of an interpreter?

This plugin may need an installed Python interpreter. 🤔

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/koxudaxi/poetry-pycharm-plugin/issues/89#issuecomment-675078582>,
or unsubscribe

**Comment by koxudaxi** [comment]
> You mean in my project or globally? I didn't have one set up yet in the project.

I ask you you have a global python interpreter.

Also,  Do you get the same problem in `Pipenv Environment` tab?
I copied the UI and logic to detect the interpreter from  `Pipenv Environment` tab.
